pipeline {
    agent {
        docker {
            image 'maven:3-alpine'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('SCM') {
      		steps {
    			git 'https://github.com/MainakB/simple-java-maven-app.git'
    		}
  		}
        stage('SonarQube analysis') {
  			steps{
    			withSonarQubeEnv('sonar-maven') {
      				sh 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:3.2:sonar'
    			}
    		}
  		}
  		stage("Quality Gate") {
            steps {
              timeout(time: 10, unit: 'MINUTES') {
                waitForQualityGate abortPipeline: true
              }
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
    }
}
